import { AppWrapper } from "@/components/app/AppWrapper";
import { Header } from "@/components/header/Header";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AppWrapper>
      <Header />
      {children}
    </AppWrapper>
  );
}
